name: Free Graphical Cloud Mac
on: workflow_dispatch

jobs:
  interactive-desktop:
    runs-on: macos-26
    steps:
      - name: Start Apple Graphical Interface and VNC Server
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -allowAccessAllUsers -privs -all
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvncpasswd -vncpasswd password123
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent

      - name: Establish Remote Connection Tunnel
        run: |
          curl -s https://amazonaws.com -o ngrok.tgz
          sudo tar -xzf ngrok.tgz -C /usr/local/bin
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          ngrok tcp 5900
